.PHONY: all

all:
	Rscript src/prepare_providers.R
	Rscript src/prepare_yolo.R
	Rscript src/prepare_com_orgs.R
	Rscript src/prepare_vendors.R
	Rscript src/prepare_day_care.R
	Rscript src/prepare_gini.R
	Rscript src/prepare_income.R
	Rscript src/prepare_insurance.R
	Rscript src/prepare_poverty.R
